flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: backend
      paths:
        - api/
      statuses:
        - type: project
          target: 100%
          threshold: 10%
